import "./globals.css"
import { Inter } from "next/font/google"

import { css, cx } from "../../styled-system/css"

const spacing = css({
  "padding": "5px",
  "margin": "0 auto",
  "maxWidth": "800px",
  "minHeight":"100vh",
  "display": "grid",
  "gridTemplateRows": "auto 1fr auto"
})
const inter = Inter({ subsets: ["latin"] })

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={cx(inter.className, spacing)}>
				<header>Header</header>
				<main>{children}</main>
				<footer>Footer</footer>
			</body>
		</html>
	)
}
